general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
    no_fade_in = true
    no_fade_out = true
}

background {
    monitor =
    color = rgb(000000)
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 20
    rounding = 0
    outer_color = rgba(ffffffff)
    inner_color = rgba(000000ff)
    font_color = rgb(ffffff)
    font_family = JetBrainsMono Nerd Font
    font_size = 16
    fade_on_empty = false
    fade_timeout = 0
    placeholder_text =
    hide_input = true
    fail_color = rgb(ff5555)
    fail_text =
    capslock_color = rgb(ffb000)
    position = 0, 0
    halign = center
    valign = center
}
