return {
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     {
  --       "nvim-telescope/telescope-fzf-native.nvim",
  --       build = "make",
  --       cond = function()
  --         return vim.fn.executable("make") == 1
  --       end,
  --     },
  --     {
  --       -- dir = "~/github/madsludvig/telescope-stregsystem",
  --       "madsludvig/telescope-stregsystem",
  --       dependencies = {
  --         "rcarriga/nvim-notify",
  --       },
  --     },
  --     { "nvim-tree/nvim-web-devicons", enabled = vim.g.have_nerd_font },
  --   },
  --
  --   cmd = { "Telescope" },
  --
  --   -- stylua: ignore
  --   keys = {
  --     vim.keymap.set("n", "<leader>-", "<cmd>Telescope stregsystem<CR>", { desc = "[-]StregSystem" }),
  --   },
  --
  --   config = function()
  --     require("telescope").setup({
  --       extensions = {
  --         ["stregsystem"] = {
  --           username = "sudo",
  --         },
  --       },
  --     })
  --
  --     -- Enable telescope extensions, if they are installed
  --     pcall(require("telescope").load_extension, "fzf")
  --     pcall(require("telescope").load_extension, "ui-select")
  --     pcall(require("telescope").load_extension, "stregsystem")
  --   end,
  -- },
}
